### ISSUE TITLE
write unit tests for tree browser - open for contributors

### ISSUE THREAD

**Issue by kashjs** [Adaptv/adapt-strap#116]
comment here if you are starting to work on this

**Comment by dmlzj** [comment]
I have a problem! I don't know how to open the tree for app start ! Could you help me? Thank you very much!

**Comment by kashjs** [comment]
Sure. Can you provide more detail? I don't know what you mean by opening the tree for app start.

**Comment by dmlzj** [comment]
I hope this tree is expand when i open the tree page，but default it is Shrinkage！

**Comment by kashjs** [comment]
Oh You have full control over what is expanded. You just need to set `_ad_expanded = true` on each node that you want to be expanded.

**Comment by dmlzj** [comment]
Thank you !  OK!
