### ISSUE TITLE
Editable rows?

### ISSUE THREAD

**Issue by uclesn** [Adaptv/adapt-strap#145]
I've been trying  find a good javascript plugin/widget/framework for creating nested grids. All the ones I found so far(ng-table, ng-grid, smart-tables) have everything but nested grids, this is the only one I have found that does that however I did not see was a way to make the table editable. If it is not included in the features can you direct me on how to do this?

**Comment by kashjs** [comment]
Currently, only way to do it is providing your own editable template for each cell. We are contemplating introducing that feature in future releases. What exactly do you need in terms of editing? (specific events etc.)

**Comment by uclesn** [comment]
Basically so that it is similar to slickgrid or jqgrid (Guriddo) .
http://www.guriddo.net/demo/treegridjs/

jqGrid does everything I would need but were looking for something 
freely available for commercial use.

Regards,
Nielsen Ucles
P: +1.561.807.1502 x 1051
F: +1.866.459.4548
E: nielsenucles@ordyx.com
Ordyx Simple, Secure, Online

CONFIDENTIALITY NOTICE: This email message is for the sole use of the 
named recipient(s) and may contain proprietary, confidential and 
privileged information. Any unauthorized review, use, disclosure, or 
distribution of this message or any attachments is expressly prohibited. 
If you are not the intended recipient, please contact the sender by 
reply email and destroy all copies of the original message.

**Comment by kashjs** [comment]
I see. Well, our ad-tree-browser component is what you need. I will be to happy you with implementation. But I am still unclear on what you mean by edit. Do you mean being able to add remove nodes to the nesting?

**Comment by uclesn** [comment]
Basically so that I can edit the data for the rows and the nested data 
for each row. For example if i have  a table displaying a list of 
customers, I want to be able to click on a customer and edit the row 
with the customer information as well as edit the data from the expanded 
table/grid.
Regards,
Nielsen Ucles
P: +1.561.807.1502 x 1051
F: +1.866.459.4548
E: nielsenucles@ordyx.com
Ordyx Simple, Secure, Online

CONFIDENTIALITY NOTICE: This email message is for the sole use of the 
named recipient(s) and may contain proprietary, confidential and 
privileged information. Any unauthorized review, use, disclosure, or 
distribution of this message or any attachments is expressly prohibited. 
If you are not the intended recipient, please contact the sender by 
reply email and destroy all copies of the original message.

**Comment by kashjs** [comment]
we have the row expand feature now. It should take care of your requirements.
