### ISSUE TITLE
question: is it worth to have two table component?

### ISSUE THREAD

**Issue by nlac** [Adaptv/adapt-strap#153]
Hi,
i'm wondering does it have advantages to keep the grid functionality in two directives? I'm almost sure that all other grid components i've seen (i've digged in a lot during my work:-), angular and non-angular ones) has only one directive that handles both ajax and local data sources. That way the writer can easily avoid some code redundances (eg. templates for headers, sorting, pagination, filtering) and is more motivated to design a feature to work with any data source (eg. when implementing a row-drag'n-drop).

**Comment by kashjs** [comment]
You are right. We are planing to merge them into one directive in next major release.

**Comment by nlac** [comment]
It's fine!
