### ISSUE TITLE
Feature request (Aol.): Ability to change style of a row/rows

### ISSUE THREAD

**Issue by vbedanov** [Adaptv/adapt-strap#155]
Need ability to change style of a row/rows based on user action. Ideally: call a function with a new style class for the selected row.

Thanks,
Vlad

**Comment by kashjs** [comment]
Working on this...

**Comment by kashjs** [comment]
v2.1.2 has been released with the requested feature.

Examples at http://adaptv.github.io/adapt-strap/.

Basically you need to provide a function in directive. The function will get called with row item. Whatever string that function returns gets applied as row class.
