### ISSUE TITLE
row-ng-class={active: item._selected}

### ISSUE THREAD

**Issue by dmlzj** [Adaptv/adapt-strap#156]
Tree Browser:  I have a problem for it: i hope it has style when it was selected,but i don't know where i should set the attribute !Could you help me ?Thank you~~!!

**Comment by kashjs** [comment]
Sure. I can help you but I need to know more about your problem. Give me all the details.

**Comment by dmlzj** [comment]
Like this:I click a item ,then this item was selected ,i hope this item has a selected css style!

**Comment by kashjs** [comment]
do this 
```html
row-ng-class={selected: item._selected}
```
in your controller
```javascript
$scope.itemClicked = function (item) {
     item._selected = true;
}
```

in your node template:
```html
<span ng-click="itemClicked(item)">{{ item.name }}</span>
```

This way any row that is selected will have selected class on it.
