### ISSUE TITLE
Parent/child data structure

### ISSUE THREAD

**Issue by sbones88** [Adaptv/adapt-strap#157]
Hello,
All the demos show the parent and child data with the same structure.  I would like to create a tree browser in which the parent row has different columns than the children rows.  i could not figure out how to do this.  Can you give an example?
Thanks!

**Comment by kashjs** [comment]
Sure. Can you give an example of data structure that you are trying to represent?

**Comment by sbones88** [comment]
Yes - json file is attached.  I am hoping to get something similar to this,
which was created using Infragistics hierarchical grid control...
[image: Inline image 1]

Thank you!
Steve


On Tue, Jan 27, 2015 at 8:46 PM, Kash Patel <notifications@github.com>
wrote:

> Sure. Can you give an example of data structure that you are trying to
> represent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adaptv/adapt-strap/issues/157#issuecomment-71780552>.
>



-- 
Steve

**Comment by kashjs** [comment]
Can you paste the json here. I am unable to see your json file in here.

**Comment by sbones88** [comment]
Yes absolutely!  Here you go...

[{"inventory":[{"LotID":"84P2-1-SR005","PartNo":"84P2-1","Description":"84P2-1","ClassCode":"SUB","Sublot":null,"ExpirationDate":"2016-10-20T00:00:00","LocationId":2380,"Location":"Cabinets","Quantity":199.0,"UomId":7,"UOM":"Linear
Feet","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":2,"Grade":"GOODGRADE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":"SL-005","OperationId":"SL","SequenceNo":0,"LastEditBy":"Administrator","LastEditAt":"2014-11-04T00:35:09","RowId":65}],"ParentClass":"SUB","ParentPart":"MOD-ST0.20-1","ParentDesc":"MOD-ST0.2-01","Version":"M","ItemNo":10,"ComponentClass":"SUB","ComponentPart":"84P2-1","ComponentDesc":"84P2-1","QtyPerAssembly":11.0,"UOM":"LF","LastEditBy":null,"LastEditAt":"0001-01-01T00:00:00","RowPointer":0},{"inventory":[{"LotID":"MT10-1-SR005","PartNo":"MT10-1","Description":"Support,
MT10, Slit for
10\"","ClassCode":"SLITROLL","Sublot":null,"ExpirationDate":"2016-10-16T00:00:00","LocationId":2380,"Location":"Cabinets","Quantity":90.0,"UomId":7,"UOM":"Linear
Feet","AutoReorder":false,"MinInvLevel":124086.15,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":2,"Grade":"GOODGRADE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":"SL-006","OperationId":"SL","SequenceNo":0,"LastEditBy":"administrator","LastEditAt":"2014-11-03T23:04:54","RowId":64}],"ParentClass":"SUB","ParentPart":"MOD-ST0.20-1","ParentDesc":"MOD-ST0.2-01","Version":"M","ItemNo":20,"ComponentClass":"SLITROLL","ComponentPart":"MT10-1","ComponentDesc":"Support,
MT10, Slit for
10\"","QtyPerAssembly":11.0,"UOM":"LF","LastEditBy":null,"LastEditAt":"0001-01-01T00:00:00","RowPointer":0},{"inventory":[{"LotID":"2100-003","PartNo":"2100","Description":"2100","ClassCode":"MLD","Sublot":null,"ExpirationDate":null,"LocationId":28,"Location":"GS1","Quantity":100.0,"UomId":1,"UOM":"Each","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":2,"Grade":"GOODGRADE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":"ML-003","OperationId":"ML","SequenceNo":0,"LastEditBy":"andrewd","LastEditAt":"2014-10-21T00:03:58","RowId":55}],"ParentClass":"SUB","ParentPart":"MOD-ST0.20-1","ParentDesc":"MOD-ST0.2-01","Version":"M","ItemNo":30,"ComponentClass":"MLD","ComponentPart":"2100","ComponentDesc":"2100","QtyPerAssembly":2.0,"UOM":"EA","LastEditBy":null,"LastEditAt":"0001-01-01T00:00:00","RowPointer":0},{"inventory":[{"LotID":"1109-002","PartNo":"1109","Description":"1109","ClassCode":"MLD","Sublot":null,"ExpirationDate":null,"LocationId":22,"Location":"PL1","Quantity":70.0,"UomId":1,"UOM":"Each","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":2,"Grade":"GOODGRADE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":"ML-002","OperationId":"ML","SequenceNo":0,"LastEditBy":"andrewd","LastEditAt":"2014-10-21T00:00:02","RowId":56},{"LotID":"1109-004","PartNo":"1109","Description":"1109","ClassCode":"MLD","Sublot":null,"ExpirationDate":"2016-10-16T00:00:00","LocationId":22,"Location":"PL1","Quantity":1010.0,"UomId":1,"UOM":"Each","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":0,"Grade":"ACCEPTABLE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":null,"OperationId":null,"SequenceNo":null,"LastEditBy":"andrewd","LastEditAt":"2014-10-16T21:29:09","RowId":70}],"ParentClass":"SUB","ParentPart":"MOD-ST0.20-1","ParentDesc":"MOD-ST0.2-01","Version":"M","ItemNo":40,"ComponentClass":"MLD","ComponentPart":"1109","ComponentDesc":"1109","QtyPerAssembly":1.0,"UOM":"EA","LastEditBy":null,"LastEditAt":"0001-01-01T00:00:00","RowPointer":0},{"inventory":[{"LotID":"ML-015","PartNo":"1101","Description":"1101","ClassCode":"MLD","Sublot":null,"ExpirationDate":"2016-10-01T00:00:00","LocationId":10,"Location":"Inspection","Quantity":89.0,"UomId":1,"UOM":"Each","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":2,"Grade":"GOODGRADE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":"WO-015","OperationId":"ML","SequenceNo":0,"LastEditBy":"administrator","LastEditAt":"2014-11-03T22:24:00","RowId":5},{"LotID":"1101-001","PartNo":"1101","Description":"1101","ClassCode":"MLD","Sublot":null,"ExpirationDate":null,"LocationId":22,"Location":"PL1","Quantity":74.0,"UomId":1,"UOM":"Each","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":2,"Grade":"GOODGRADE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":"ML-001","OperationId":"ML","SequenceNo":0,"LastEditBy":"administrator","LastEditAt":"2014-11-03T22:50:24","RowId":57},{"LotID":"1101-004","PartNo":"1101","Description":"1101","ClassCode":"MLD","Sublot":null,"ExpirationDate":"2016-10-16T00:00:00","LocationId":22,"Location":"PL1","Quantity":1000.0,"UomId":1,"UOM":"Each","AutoReorder":false,"MinInvLevel":0.0,"ReorderQty":0.0,"Purchased":false,"Sold":false,"GradeCd":0,"Grade":"ACCEPTABLE","StatusCd":2,"Status":"GOODSTATE","WorkOrder":null,"OperationId":null,"SequenceNo":null,"LastEditBy":"andrewd","LastEditAt":"2014-10-16T21:29:09","RowId":71}],"ParentClass":"SUB","ParentPart":"MOD-ST0.20-1","ParentDesc":"MOD-ST0.2-01","Version":"M","ItemNo":50,"ComponentClass":"MLD","ComponentPart":"1101","ComponentDesc":"1101","QtyPerAssembly":1.0,"UOM":"EA","LastEditBy":null,"LastEditAt":"0001-01-01T00:00:00","RowPointer":0}]

Steve



On Sun, Feb 1, 2015 at 12:05 AM, Kash Patel <notifications@github.com>
wrote:

> Can you paste the json here. I am unable to see your json file in here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adaptv/adapt-strap/issues/157#issuecomment-72355800>.
>



-- 
Steve

**Comment by kashjs** [comment]
You can create a parent object like this

```javascript
$scope.parent = {
    inventory: // here you assign entire array that you posted in your comment.
}
```
in your html:

```html
 <ad-tree-browser 
                   tree-name="treeDemoBordered"
                   tree-root="parent"
                   child-node="inventory"
                   children-padding="15"
                   node-header-url="src/treebrowser/docs/treeHeader.html"
                   node-template-url="src/treebrowser/docs/treeNode.html">
  </ad-tree-browser>
```
