### ISSUE TITLE
Tableajax enhancement--implement callback method when a row is expanded

### ISSUE THREAD

**Issue by lamquoc** [Adaptv/adapt-strap#158]
Currently, when a row in Tableajax is expanded, only fields in the item object are available. It would be nice if there is a way to customize this, e.g., having a callback that takes item as input parameter

**Comment by kashjs** [comment]
Yes..... This is a known drawback. We are working on a callback that gets called whenever an item is expanded or collapsed. You can load additional data or do any data manipulation to load it. This is very good for lazy loading additional information. We will fix it and provide new release in next few days.. stay tuned.

**Comment by kashjs** [comment]
`row-expand-callback` attribute has been added to table components that allow you to append additional properties to your object on expand.
