### ISSUE TITLE
Filter on some columns only

### ISSUE THREAD

**Issue by corientdev** [Adaptv/adapt-strap#164]
Hi Kash,

Hope you are doing good.

Congrats man for the improvement in the library. 
Just wanted to know if i have 5 column and i want to filter on only 3 columns global filter i am talking about i.e search the text from a single textbox in 3 defined columns only not in all columns. How can we do it?

Hope i am clear with my question.

Thanks!

**Comment by kashjs** [comment]
Hi Vishal,

I am doing well. Thanks for asking.

You can always pass filter expression object to `search-text` attribute.

like this: `search-text="models.searchText"`

```javascript
function onSearchInputKeyUp () {
        // if you do it this way, it will only search the name and year properties
        $scope.models.searchText = {'name': 'Audi', 'year': 2009};    
}
```
Thanks,
Kash

**Comment by corientdev** [comment]
You are a hero kash. Stay Blessed...
