### ISSUE TITLE
Hiding a node on the tree leaves a the empty div from the ng-repeat (Tree browser)

### ISSUE THREAD

**Issue by amalahussein** [Adaptv/adapt-strap#175]
Hi---we need to hide a node on the tree, and whenever we attempt to hide it with an ng-if or ng-hide, the contents of the node are gone, but the empty div on the DOM still remains. Its there anyway around this without a fresh update from the DB? (when the user clicks 'hide' its completely hidden as if it were popped off)

**Comment by kashjs** [comment]
With current interface, you can use `row-ng-class` to add a hiding class to the row.

This is how you can do it:
```css
.hide-node {
  display: none;
}
```
```html
<ad-tree-browser row-ng-class="{'hide-node': item._hide}"></ad-tree-browser>
```
After that, any node with `_hide = true` will be hidden.


Hope this helps...

**Comment by amalahussein** [comment]
Hey Kash thank worked beauitfully!!! Thanks for such a quick response---so my problem now is that when I hide the node there is a little 1px border that is left behind b/c I have set bordered=true in the directive attributes. Is there anywhere I can override this when I hide or, will I have to just remove the border and apply my own CSS styling to the the tree to get a border on each node?

**Comment by kashjs** [comment]
Let me investigate this.. i will get back soon

**Comment by amalahussein** [comment]
Your awesome!! Thanks :+1:
