### ISSUE TITLE
question about headers under tree browser

### ISSUE THREAD

**Issue by rrutter** [Adaptv/adapt-strap#177]
Just curious if it is possible to use a different header template for the child nodes of the tree browser demo?

So parent would have it's own header template
children node would have it's own header unique template

thanks!

**Comment by kashjs** [comment]
so there would be multiple headers on tree?

**Comment by rrutter** [comment]
The issue is multiple nesting within children.
I was going to use the 1st set of children to apply the header to. then nest the 2nd set under. (seems to work).

**Comment by kashjs** [comment]
nope. I am having hard time understanding requirement. I guess a snapshot would help of what you are trying to achieve visually.

**Comment by rrutter** [comment]
Thanks for your responses Kashjs.

Here is an image of my use case.
http://tinypic.com/r/11ilrwk/8

regards,
-russ

**Comment by kashjs** [comment]
Oh...
You need to use table-lite with expandable row feature. http://jsfiddle.net/kashjs/gt8Ljspf/
Let me know if that works.

**Comment by rrutter** [comment]
I did go this route earlier, however the expandable row did not support children's children and they showed up on all rows.

**Comment by kashjs** [comment]
Can you share the exact data object for that image

**Comment by rrutter** [comment]
Sure. The idea is to show repair orders in a grid at first and then when they clicked to expand it, a rest call would retrieve the jobs.

So initial load 

            repairOrders: [
                {
                    id: 1,
                    orderId: '122450',
                    roClosure: '01/01/2013',
                    location: 'MI',
                    desc:"BODY REPAIR CITIZEN",
                    count: '3',
                    indicators:"C",
                    mileage: "60,560 Miles"
                },
                {
                    id: 2,
                    orderId: '122457',
                    roClosure: '02/01/2013',
                    location: 'MI',
                    desc:"ELECTRICAL DEPT",
                    count: '1',
                    indicators:"C",
                    mileage: "60,312 Miles"
                },
                {
                    id: 3,
                    orderId: '705772',
                    roClosure: '04/03/2014',
                    location: 'MI',
                    desc:"REPLACE 4 TIRES",
                    count: '8',
                    indicators:"C, I, W",
                    mileage: "56949 Miles"
                }
            ]

by expanding on a specific orderId i would make another restful call and retrieve the info like so....

        jobs:   [
            {
                id: 1,
                jobNumber: '12',
                opCodeDMS: '14CVZMULTI - MULTIPOINT',
                opCodeStandard: '0204',
                jobType:"CUSTOMER PAY",
                dept: 'SERVICE'
            },
            {
                id: 2,
                jobNumber: '13',
                opCodeDMS: '14CVZMULTI - MULTIPOINT',
                opCodeStandard: '0204',
                jobType:"CUSTOMER PAY",
                dept: 'SERVICE',
                parts: 
                    [
                        {qty: '1', partNum: 'PK457G', Desc: 'LOF'}, 
                        {qty: '1', partNum: '12605566', Desc: 'FILTER 1.836'},
                        {qty: '5', partNum: 'GM89021593', Desc: 'OIL 8.800'}
                        
                    ]
            },
            {
                id: 3,
                jobNumber: '14',
                opCodeDMS: '14CVZMULTI - MULTIPOINT',
                opCodeStandard: '0204',
                jobType:"CUSTOMER PAY",
                dept: 'SERVICE'
            }
        ]

I really thank you for your time in this. This seems like the best route to go.

**Comment by kashjs** [comment]
Perfect. You can still use the table component for this.

I have created an example fiddle for you. 
http://jsfiddle.net/kashjs/cr4vyqzf/2/

Thanks.

**Comment by rrutter** [comment]
Thank you for that example kashjs. I am curious how i would pull the parts information? would i just specify that the jobs.parts as the source and roll with that?

You are incredibly helpful!

**Comment by kashjs** [comment]
so inside any expand template, you have access to the item object. item object it the current row object.

You can do it like this  {{ item.parts }} in your job expand template. You can render any information on the parts as you want in your template.

**Comment by rrutter** [comment]
Thanks so much kash for your assistance and awesome widget!
