### ISSUE TITLE
incorrect url of sortIcons.tpl

### ISSUE THREAD

**Issue by nlac** [Adaptv/adapt-strap#178]
In the .tpl file, ng-include directives refer to "src/tableajax/sortIcon.html" but the default template string is stored with url "tablelite/sortIcons.html" into the $templateCache -> no sort icons appear, 404 error for sortIcons.html

**Comment by kashjs** [comment]
interesting... Let me take a look.

**Comment by nlac** [comment]
Eh sorry, a lot of typos i've made above. The correct description:

In adapt-strap.tpl.js, 
```'tablelite/sortIcons.html'``` - the key with which the default template string has been put into the $templateCache, near line 143,
```'src/tablelite/sortIcons.html'``` - url in ```<ng-include>``` near line 111.

I think the two urls should be the same.
