### ISSUE TITLE
Draggable: Last drop over element persistent even after drop leave.

### ISSUE THREAD

**Issue by darro87** [Adaptv/adapt-strap#181]
If i drag over a droppable element, but decide to abort this drag, the item still drops into the last droppable container I moved over even if i'm no longer over it.

Summary: Can't cancel drag once drop-over triggered

**Comment by kashjs** [comment]
@bomsy can you look into this?

**Comment by darro87** [comment]
Any suggestions or workarounds in the meanwhile at least?

**Comment by bomsy** [comment]
Are you using the ad-drop-leave event?

**Comment by darro87** [comment]
yep. but the ad-drop-end still fires and drops the item into the last over container.

**Comment by bomsy** [comment]
do you have an example we can look at?

**Comment by bomsy** [comment]
Not sure if you are doing this already, but try setting $dropElement to null in the on-drop-leave event

**Comment by darro87** [comment]
http://adaptv.github.io/adapt-strap/##draggable

issue present even on the example page linked above.

no dice on the null, the scope of the dropelement for the ad-drop-end isn't the same for ad-drop-leave, so it doesn't work..

**Comment by darro87** [comment]
Can't seem to work my way around it...

**Comment by bomsy** [comment]
Hey,
will look into fixing this for you. Would probably kill the $dropElement on drop leave.

**Comment by darro87** [comment]
Thanks! When will I be able to download an updated build with this fix?

**Comment by adamsrobw** [comment]
I think you can now. It was merged

**Comment by kashjs** [comment]
A new minor version will be released soon...

**Comment by kashjs** [comment]
v2.2.5 has been released with the fix.

**Comment by darro87** [comment]
Thanks..gona test now

Appreciate the help :D

**Comment by darro87** [comment]
Worked like a charm, thanks guys!

**Comment by bomsy** [comment]
Changed the implementation for this, see exapmles http://adaptv.github.io/adapt-strap/##draggable

See pull request 
https://github.com/Adaptv/adapt-strap/pull/204
