### ISSUE TITLE
Filter nested properties table-lite

### ISSUE THREAD

**Issue by jack10** [Adaptv/adapt-strap#182]
Hi Kash,

i got a problem, were I want to filter by nested properties in table-lite. 

```coffeescript
@locationDefinition = [
        columnHeaderDisplayName: 'Category Name'
        displayProperty: 'category.name'
        sortKey: 'category.name'
        columnSearchProperty: 'category.name'
        visible: true
]
```

[$filter('filter')](https://github.com/Adaptv/adapt-strap/blob/master/src/tablelite/tablelite.js#L89) does not allow nested properties in this form:

```JSON
{"category.name":"W"}
```

One solution would be to allow to pass a function to the `columnSearchProperty`. Or supply the `$filter` function with an object without the `.` in the key:

```JSON
{"category": {"name": "W"}}
```
Greetz
Jack

**Comment by kashjs** [comment]
it might just work, have you tried doing it?

**Comment by jack10** [comment]
yes of course,

but i always get an empty set back, i made a breakpoint at [tablelit.js#L89](https://github.com/Adaptv/adapt-strap/blob/master/src/tablelite/tablelite.js#L89) and tested both forms..

```JSON
{"category.name":"W"}
```
this one give me an empty set back.

```JSON
{"category": {"name": "W"}}
```
this one gives me the set back which is filtered right.

**Comment by kashjs** [comment]
v 2.2.4 has been released with the fix.

It will respect the dots in the string now.

**Comment by jack10** [comment]
wow, thank you for the fast fix.
