### ISSUE TITLE
Tree view: force refresh in controller after modifying the data source

### ISSUE THREAD

**Issue by FaycalD** [Adaptv/adapt-strap#186]
Hi,

After loading the tree for the first time, some actions are available to the user. These actions have an impact on the datasource (some nodes can be added and removed). When we add an element, it's instantly displayed but when we delete an element a blank line persists.

Is there any tree refresh feature ? How can we avoid the mentionned behavior ?

Thank you.

**Comment by kashjs** [comment]
interesting... that must be a bug. Let me try to reproduce it.

**Comment by kashjs** [comment]
i am unable to reproduce this. Are you sure you are properly removing the node. Send me the screenshot as well as the logic that you are using to remove nodes.

**Comment by FaycalD** [comment]
Here is the logic

function deleteFromTree(arr, delId){
            for(var i = 0; i < arr.length; i++){
                if(arr[i].childElements.length > 0){
                    if(arr[i].id == delId){
                        delete arr[i]
                    }
                    else {
                        arr[i]._ad_expanded = false;
                        deleteFromTree(arr[i].childElements, delId);
                    }
                }else{
                    if(arr[i].id == delId){
                        delete arr[i]
                    }
                }
            }
        }
$scope.loadAll = function () {
            $scope.bdeslines = {};
            $scope.bdeslines.childElements = [];
            Bdesline.query_dom({id: -1}).$promise.then(function (result) {
                $scope.bdeslines.childElements = result;
            });
        };

        $scope.deleteElement = function(delId){
            deleteFromTree($scope.bdeslines.childElements, delId);
        };

And here is the screenshot
![capture d ecran 2015-05-26 a 22 48 44](https://cloud.githubusercontent.com/assets/10898797/7823172/f9f1892e-03f9-11e5-9053-790b02c86ed0.png)

**Comment by kashjs** [comment]
ok so here is the problem. You are not deleting the child. You are actually setting it to undefined.

lets say you want to delete first element in `x = [1,2];`
```
delete x[0]; //=> [undefined, 2] --- wrong way
x.splice(0,1); //=> [2] --- correct way
```

You need to use [array.splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) instead of delete.

Note: if you switch to splice, it is good idea to loop through the array in reverse direction!!

**Comment by FaycalD** [comment]
You are absolutely right !

Thank you very much.
