### ISSUE TITLE
is there is any way to expand the first node in treeBrowser by default?

### ISSUE THREAD

**Issue by sivaecekrr** [Adaptv/adapt-strap#191]
is there is any way to expand the first node in treeBrowser by default. ? 
Please suggest ??

**Comment by kashjs** [comment]
you just need to set `_ad_expanded = true` on whichever node you want expanded.

**Comment by sivaecekrr** [comment]
can please elaborate where i exactly need to do it ?. Thanks in advance.

**Comment by sivaecekrr** [comment]
Its working now. Thanks.

**Comment by sivaecekrr** [comment]
To my understanding i have added _ad_expanded = true in particular node in JSON. But is there any other way to do this. ?. Thanks in advance.

**Comment by kashjs** [comment]
Currently that is the only way possible.

**Comment by sivaecekrr** [comment]
ok cool. Will use it in that way itself. Thanks. :+1:
