### ISSUE TITLE
on-drag-change don't work on v.2.3.0

### ISSUE THREAD

**Issue by Titou74** [Adaptv/adapt-strap#200]
Hello,
The "on-drag-change" function don't work on table-lite component with version 2.3.0.
http://jsfiddle.net/kashjs/gt8Ljspf/

**Comment by bomsy** [comment]
Hey, i think i know the problem..looking into it.

**Comment by kashjs** [comment]
Thanks @bomsy

**Comment by Titou74** [comment]
Bug present since version 2.2.5 (work correctly on version 2.2.4)

**Comment by Titou74** [comment]
Not work on 2.3.1 ...

**Comment by adamsrobw** [comment]
We will get this fixed this week. Apologies. One developer did the selfish
thing and went and got married. Another is traveling.

-R

Sent from my iPhone

On Jul 6, 2015, at 4:05 AM, Titou74 <notifications@github.com> wrote:

Not work on 2.3.1 ...

—
Reply to this email directly or view it on GitHub
<https://github.com/Adaptv/adapt-strap/issues/200#issuecomment-118767154>.

**Comment by Titou74** [comment]
No problems, I report just the problems I can found ;-)

**Comment by bomsy** [comment]
I've been working on fixing this. The fix is quite tricky and the change that was made affects how drag n drop works... almost done.

**Comment by bomsy** [comment]
https://github.com/Adaptv/adapt-strap/pull/204
