### ISSUE TITLE
Tablite component sorting on drag n drop

### ISSUE THREAD

**Issue by bomsy** [Adaptv/adapt-strap#202]
The tablite component is sorting on drag n drop, so the ordering of items get mangled up.
http://adaptv.github.io/adapt-strap/##tablelite
1. Drag any item on the list
2. The list shuffles and item gets lost.

@kashjs should we sorting here https://github.com/Adaptv/adapt-strap/blob/master/src/utils/utils.js#L303.
Because the  `loadPage`  function gets called on a drag and drop, once there is a drop and sortKey is `true` the list reorders.

**Comment by kashjs** [comment]
yah this is bug....

**Comment by bomsy** [comment]
https://github.com/Adaptv/adapt-strap/pull/204

**Comment by kashjs** [comment]
seems like this is fixed?? if so can you close it.
