### ISSUE TITLE
Drag and drop demo not working

### ISSUE THREAD

**Issue by alinmindroc** [Adaptv/adapt-strap#206]
Hi, the drag and drop jsFiddle doesn't seem to work:
http://jsfiddle.net/kashjs/n2gxobf7/

It seems that the way you get the id of the dropElement gives an error in the console. I have found a workaround, to replace line 64:
      "if (dropElement.attr('id') === 'my-basket') {"
with
      "if (dropElement.el.context.id === 'my-basket') {"

**Comment by bomsy** [comment]
Yeah! it looks like the documentation had not been updated.
to get the actual element you do `dropElement.el` instead of `dropElement`

**Comment by bomsy** [comment]
Ah it looks like the jsfiddle has not been updateed.

**Comment by kashjs** [comment]
Fixed!!
