### ISSUE TITLE
TableAjax: Pagination page sizes control disappears on certain condition

### ISSUE THREAD

**Issue by lamquoc** [Adaptv/adapt-strap#211]
If the total number of items in the underlying models in Table Ajax is less then a page size, the entire page sizes control is not displayed.
For example, page sizes is set at [5, 10, 20] and the total is 15. Initially, the control is visible--page size is 5 by default. If page size is 20, the control does not get rendered.

**Comment by kashjs** [comment]
should be fixed in latest version
