### ISSUE TITLE
Allow custom styling of expand/collapse buttons

### ISSUE THREAD

**Issue by noahmonster** [Adaptv/adapt-strap#218]
I'd like to be able to style the expand and collapse buttons on the tree browser to fit better with my app.  Is there a way to pass in the style class(es) that I want to use?  Perhaps I can override the styling in my own app?

**Comment by kashjs** [comment]
You can already do this. Take a look at configure icons section on the right under Getting Started. Let me know if that works for you.

**Comment by noahmonster** [comment]
Good enough.  Thanks for the tip.  I guess it would help if I read the documentation :-P
