### ISSUE TITLE
How can i programmatically close the Expanded Row table lite

### ISSUE THREAD

**Issue by corientdev** [Adaptv/adapt-strap#239]
How can i programmatically close the Expanded Row table lite from my controller. because what i am doing is basically i am showing an update fields and Update record button in the expanded template so on update record click it should hide the expanded row

**Comment by kashjs** [comment]
Currently there is no API to do that. But it would be a nice enhancement.

**Comment by corientdev** [comment]
so when can we expect this :dancers:

**Comment by corientdev** [comment]
or any hack for now? :D

**Comment by corientdev** [comment]
Please help.. Need this urgently any quick way to achieve it?

**Comment by corientdev** [comment]
Kash?

**Comment by adamsrobw** [comment]
Anyone is capable of doing the work and submitting a pull request.

Sent from my iPhone

On Feb 3, 2016, at 4:45 AM, Vishal Vishwakarma <notifications@github.com>
wrote:

Kash?

—
Reply to this email directly or view it on GitHub
<https://github.com/Adaptv/adapt-strap/issues/239#issuecomment-179128782>.

**Comment by corientdev** [comment]
request you to please guide me some work around for now. Any easy dirty way?

**Comment by kashjs** [comment]
Give me a day and I will get back to you.

**Comment by kashjs** [comment]
did you want to just collapseAll programmatically?

**Comment by corientdev** [comment]
No i want that particular opened row to close like it happens when click on the row `minus` button

**Comment by corientdev** [comment]
kash? :-(

**Comment by kashjs** [comment]
this will take a little time as i want to properly design the interface for external actions.

**Comment by corientdev** [comment]
any work around for now? Please??

**Comment by kashjs** [comment]
this is super hacky but you can try it:

basically target the expand button for the row that you need to close and trigger click event on it. 
```javascript
$('.glyphicon-plus-sign').trigger('click');
```
Please let me know if it worked for you.

**Comment by corientdev** [comment]
not working may be because that i class don't hold that click event

**Comment by kashjs** [comment]
The interface has been exposed in master branch. It is not released yet but you can start using it off of master branch. 
Here is an example on how to use it.
https://github.com/Adaptv/adapt-strap/blob/master/src/tablelite/docs/tablelite.ctrl.js#L156

**Comment by corientdev** [comment]
genius you are.. works like charm billion thanks!
