### ISSUE TITLE
How can I bind the grid to dynamic data?

### ISSUE THREAD

**Issue by msgirlperl** [Adaptv/adapt-strap#250]
I got your example working for the tree-browser (thank you!).

Now, I'm trying to bind it to my web API call.  It's not working, so I tried moving your test data inside the call, but it's still not working.  Any ideas?  I tried calling $apply() but got an error that a digest was already in progress.

```
angular.module('adaptv.adaptStrapDocs')
  .controller('treebrowserCtrl', ['$scope', function ($scope) {

MyFunctionThatWillEventuallyReturnData(...).
.then(function (pResponse) {                 

// $scope.root now defined inside of my function                    

 $scope.root = ...
    
},function (pResponse) { MyErrorHandler(pResponse, $scope); });
  }]);
```

**Comment by kashjs** [comment]
Try wrapping tree-browser inside ng-if like this:

```html
<div ng-if="root">
    <ad-tree-browser tree-root="root"></ad-tree-browser>
</div>
```

**Comment by msgirlperl** [comment]
Thank you!  Would you mind explaining?  Is it because the browser tries to render the tree before the scope.root has been assigned?  And then it doesn't update?

**Comment by kashjs** [comment]
that is correct. Tree root needs to be defined before you pass it to tree-browser. once it is rendered, it will have two way binding with its children and inner structure.

**Comment by msgirlperl** [comment]
Thanks, Kash!  Really appreciate the prompt replies!

I'm not working on the lazy loading - wish me luck :-) (I'm new to angular
as you may have guessed!)

**Comment by kashjs** [comment]
good luck. reach out if you get stuck.
